### ISSUE TITLE
Device type problem after adding secondary_entities:

### ISSUE THREAD

**Issue by malosaa** [make-all/tuya-local#2004]
**Describe the bug**
When creating a new device and adding the yaml it does not get detected at all, getting different device types.
however i did find out when removing secondary_entities: from the yaml it does get detected.

Even if i use some other yaml whats already supported and just add secondary_entities: with the correct data it does not get detected when adding the device.

**To Reproduce**
Just create a working yaml, add the data like this :
```
name: MY DEVICE
products:
  - id: MY PRODUCT ID
primary_entity:
  entity: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch
secondary_entities:
  - entity: button
    name: Filter replaced
    icon: "mdi:air-filter"
    category: config
    dps:
      - id: 104
        type: boolean
        name: button
```
when using this bit of code while adding my device, it does not get detected when selecting device type.

however when i do this its detected:
```
name: MY DEVICE
products:
  - id: MY PRODUCT ID
primary_entity:
  entity: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch
```

**Expected behavior**
that it works normal.

**Additional context**

If the bug involves a device, then please include device diagnostics from
```
Detected blocking call to open inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/tuya_local/config_flow.py", line 436, in async_step_local return await self.async_step_select_type() File "/config/custom_components/tuya_local/config_flow.py", line 474, in async_step_select_type async for type in self.device.async_possible_types(): File "/config/custom_components/tuya_local/device.py", line 360, in async_possible_types for match in possible_matches(cached_state): File "/config/custom_components/tuya_local/helpers/device_config.py", line 982, in possible_matches parsed = TuyaDeviceConfig(cfg) File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__ self._config = load_yaml(filename)
```

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:489
integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 12:34:43 AM (13 occurrences)
Last logged: 1:07:01 AM

Report this to https://github.com/make-all/tuya-local/issues
```

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment]
This is due to device behaviour, if you included the log message with dps included in the message, then the solution would become obvious.  The log messages you did include are the following log message telling you to report that, and another issue caused by HA 2024.6 changes, which was fixed in the 2024.6.0 release a couple of days ago.

**Comment by malosaa** [comment]
Thanks for your feedback, well i'm new to this tuya-local.
So you said "f you included the log message with dps included in the message"  
so if i understand i need to debug it ?

still don't understand why it works when updating a wrong detected device with my code, before pressing submit.
I would like to solve this, and if i know what the problem is i will add more device support on this github as now i can't. 
But right now please point me at the right direction.

regards

**Comment by malosaa** [comment]
@make-all 

i did some research and here  i will post the issue again, my dps are correct 

```
name: Hydrate Ultra
products:
  - id: cuw2k3ho3e25fade  

primary_entity:
  entity: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch

secondary_entities:
  - entity: light
    name: Led light
    icon: "mdi:brightness-6"
    category: config
    dps:
      - id: 102
        type: boolean
        name: switch
        icon: "mdi:brightness-6"
      - id: 103
        name: Led brightness
        type: integer
        range:
          min: 1
          max: 10
  - entity: button
    name: Filter replaced
    icon: "mdi:air-filter"
    category: config
    dps:
      - id: 104
        type: boolean
        name: button
  - entity: sensor
    name: Filter life
    icon: "mdi:air-filter"
    category: diagnostic
    dps:
      - id: 104
        type: integer
        name: sensor
        precision: 0
        range:
          min: 0
          max: 43200
        mapping:
          - scale: 1440  # minutes => days
            invert: true
        unit: d
  - entity: button
    name: Pump cleaned
    icon: "mdi:pump"
    category: config
    dps:
      - id: 105
        type: boolean
        name: button
  - entity: sensor
    name: Pump maintenance
    icon: "mdi:pump"
    category: diagnostic
    dps:
      - id: 105
        type: integer
        name: sensor
        precision: 0
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 1440
            invert: true
        unit: d
  - entity: sensor
    name: Water quality
    icon: "mdi:water"
    category: diagnostic
    dps:
      - id: 106
        type: integer
        name: sensor
        unit: TDS
  - entity: switch
    name: UV sterilization
    icon: "mdi:flash"
    category: config
    dps:
      - id: 107
        type: boolean
        name: switch
  - entity: sensor
    name: Water level
    icon: "mdi:water"
    category: diagnostic
    dps:
      - id: 108
        type: integer
        name: sensor
        mapping:
          - dps_val: "1"
            value: 1
          - dps_val: "2"
            value: 2
          - dps_val: "3"
            value: 3
          - dps_val: "4"
            value: 4
  - entity: sensor
    name: UV runtime
    icon: "mdi:timer-outline"
    category: diagnostic
    dps:
      - id: 109
        type: integer
        name: sensor
        unit: s
``` 

![image](https://github.com/make-all/tuya-local/assets/13116501/6a1a8f78-d81b-4ee7-b366-5cf316169eed)


when exmam the code its almost identical with the dps

```
name: QOTO 03 sprinkler controller
primary_entity:
  entity: valve
  class: water
  dps:
    - id: 102
      type: integer
      name: valve
      mapping:
        - step: 5
secondary_entities:
  - entity: number
    icon: "mdi:pipe-valve"
    category: config
    deprecated: valve
    dps:
      - id: 102
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 100
        mapping:
          - step: 5
  - entity: sensor
    category: diagnostic
    icon: "mdi:valve"
    name: Open
    dps:
      - id: 103
        name: sensor
        type: integer
        unit: "%"
  - entity: sensor
    category: diagnostic
    translation_key: time_remaining
    class: duration
    dps:
      - id: 104
        name: sensor
        type: integer
        unit: s
  - entity: number
    category: config
    translation_key: timer
    dps:
      - id: 105
        type: integer
        name: value
        unit: s
        range:
          min: 0
          max: 86399
  - entity: binary_sensor
    category: diagnostic
    class: problem
    dps:
      - id: 108
        name: sensor
        type: integer
        mapping:
          - dps_val: 0
            value: false
          - value: true
```

My dps



```
{
  "result": {
    "properties": [
      {
        "code": "power",
        "custom_name": "",
        "dp_id": 101,
        "time": 1718172165137,
        "value": true
      },
      {
        "code": "bright_value",
        "custom_name": "",
        "dp_id": 102,
        "time": 1718172158974,
        "value": 1
      },
      {
        "code": "water_alarm",
        "custom_name": "",
        "dp_id": 103,
        "time": 1718176476518,
        "value": 71
      },
      {
        "code": "filter_alarm",
        "custom_name": "",
        "dp_id": 104,
        "time": 1718176482526,
        "value": 2595
      },
      {
        "code": "pump_alarm",
        "custom_name": "",
        "dp_id": 105,
        "time": 1718176422661,
        "value": 2594
      },
      {
        "code": "tds",
        "custom_name": "",
        "dp_id": 106,
        "time": 1718176464555,
        "value": 137
      },
      {
        "code": "uv",
        "custom_name": "",
        "dp_id": 107,
        "time": 1718175055572,
        "value": true
      },
      {
        "code": "water_level",
        "custom_name": "",
        "dp_id": 108,
        "time": 1718172158974,
        "value": 4
      },
      {
        "code": "uvruntime",
        "custom_name": "",
        "dp_id": 109,
        "time": 1718175237297,
        "value": 0
      },
      {
        "code": "uvsection",
        "custom_name": "",
        "dp_id": 110,
        "time": 1680879964898,
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1718176488525,
  "tid": "74115154288b11ef9e3b1acebe103cd3"
}
```
