### ISSUE TITLE
ElectriQ EcoSilent12HPW does not work correctly with electriq_ecosilent14hpw_aircon

### ISSUE THREAD

**Issue by XargsUK** [make-all/tuya-local#3210]
### Description

I'm experiencing an issue with the ElectriQ EcoSilent12HPW air conditioner configuration. When using the existing `electriq_ecosilent14hpw_aircon` configuration (which was [suggested](https://github.com/make-all/tuya-local/pull/3136) as compatible), there are problems with the HVAC mode mappings - specifically when setting to Auto mode and when the device is in smartcool mode. 

> [!NOTE]
> I'm raising this as an issue rather than requesting a new device because the PR for adding the ElectriQ EcoSilent12HPW (#3136) was closed with the comment that the "Device is the same as already supported 14HPW". However, in practice, the configurations have meaningful differences that affect functionality. This issue documents the specific behavioral differences to help improve compatibility.

### Steps to reproduce

1. Configure a new ElectriQ EcoSilent12HPW using the `electriq_ecosilent14hpw_aircon` configuration in Home Assistant
2. Try setting the HVAC mode to "Auto" in the Home Assistant UI
3. Observe that the physical device switches to "Cool" mode instead of "Auto/smartcool"
4. Set the device to "smartcool" mode using the physical controls
5. Observe that Home Assistant reports the state as "unknown"

### Expected behaviour

1. When setting to "Auto" mode in Home Assistant, the device should switch to "smartcool" mode
2. When the device is in "smartcool" mode, Home Assistant should correctly report the state as "Auto"

### Additional context

After analysing both configuration files, I've identified the key differences that explain why my PR configuration works correctly while the existing one doesn't:

1. **Fan mode mapping differences:**

   The 12HPW config in my PR has conditional mappings based on hvac_mode (whether the unit is on or off):

   ```yaml
   - id: 5
     name: fan_mode
     type: string
     mapping:
       - dps_val: "f1"
         constraint: hvac_mode
         conditions:
           - dps_val: false
             value: "off"
           - dps_val: true
             value: low
       # Similar pattern for other fan modes
   ```

While the 14HPW config uses direct mappings without these conditions:

   ```yaml
   - id: 5
     name: fan_mode
     type: string
     mapping:
       - dps_val: "f1"
         value: low
       - dps_val: "f2"
         value: diffuse
       # Direct mappings without constraints
   ```

2. **HVAC mode order differences:**
   - 12HPW: cool, fan, smartcool, dry, heat
   - 14HPW: cool, fan, heat, smartcool, dry

Despite being told that "Device is the same as already supported 14HPW" in the PR comments (https://github.com/make-all/tuya-local/pull/3136), the actual behaviour demonstrates that there are important differences in how the device handles state transitions or reports states.

I suggest either:

1. Merging my dedicated 12HPW configuration which correctly handles the mode mappings, or
2. Updating the 14HPW configuration to include the conditional fan mode mapping and correct mode order to support both device models properly

If you require anything else, feel free to give me a shout! 

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [ ] This is not requesting addition of a new device.

**Comment by XargsUK** [comment]
Just to confirm, is the ElectriQ EcoSilent12HPW supported by tuya-local?

I'm in a bit of a confusing situation because:
1. My PR adding support for the EcoSilent12HPW (#3136) was rejected with the comment "Device is the same as already supported 14HPW"
2. This suggested the EcoSilent12HPW is supported through the 14HPW configuration
3. However, when I use the 14HPW configuration, I encounter the behavioural issues described above
4. When I try to report this as a bug, the "This is not requesting addition of a new device" checkbox was unchecked.

I'm trying to understand the correct path forward:
- Should I be submitting this as a request for a new device (despite the previous PR rejection)?
- Is this a bug in the existing 14HPW configuration that should be fixed?
- Or is there a preferred way to handle devices that are similar but have functional differences?

**Comment by make-all** [comment]
1. This is pointless additional complexity that doesn't solve any problem. When the hvac_mode is off, the whole device is off, so it makes no real difference what the fan mode is.
2. The order of hvac_mode within the config has no impact on functionality, and they are anyway sorted alphabetically or presented in a fixed order in the UI, depending on which card is used.

It might help if you describe the actual problem you are seeing, instead of just claiming "it doesn't work properly" and proposing a solution.

**Comment by XargsUK** [comment]
> It might help if you describe the actual problem you are seeing, instead of just claiming "it doesn't work properly" and proposing a solution.

Thanks for the quick reply! Simply put, using electriq_ecosilent14hpw_aircon doesn't work correctly on electriq_ecosilent12hpw in the following ways:

1. If the air conditioner is set to Auto on the device (not in Home Assistant), then the state reflected in Home Assistant is `Unknown`. 
2. If the air conditioner is set to Auto in Home Assistant, the air conditioner is set to `Cool`, rather than `Smart Cool`. 

Now reviewing the code, this is my best understanding; I'm not going to suggest a fix for it though. 

When processing a DPS value with constraints (like the fan mode in my 12HPW config), the system looks up the current state of the constrained property like `hvac_mode` to select the correct condition. 

https://github.com/make-all/tuya-local/blob/dda598f81b6ef650485ae664efbf1797dab9b5f0/custom_components/tuya_local/helpers/device_config.py#L866-L889

In the logs when running tuya-local from my PR using the 12HPW configuration, I can see the fan mode being properly processed:

```
2025-05-01 14:41:33.576 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] ElectriQ EcoSilent12HPW: Mapped dps 5 value from f5 to top
```

But when using the 14HPW configuration in this repo for the same device, when the device returns Boolean True for the hvac_mode and is in "smartcool" mode, I see:
```
2025-05-01 14:52:38.494 WARNING (MainThread) [custom_components.tuya_local.climate] electriq_ecosilent14hpw_aircon.yaml/climate: Unrecognised HVAC Mode of True ignored
```

The method `get_values_to_set`) showed me how values are sent to the device:
https://github.com/make-all/tuya-local/blob/dda598f81b6ef650485ae664efbf1797dab9b5f0/custom_components/tuya_local/helpers/device_config.py#L906-L913

https://github.com/make-all/tuya-local/blob/dda598f81b6ef650485ae664efbf1797dab9b5f0/custom_components/tuya_local/helpers/device_config.py#L928-L949

This shows that "so it makes no real difference what the fan mode is" isn't correct, as it ultimately impacts what values are sent to the device. 

12HPW PR: 
`2025-05-01 14:41:33.576 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] ElectriQ EcoSilent12HPW: Mapped dps 1 value from True to auto`

14HPW in this repo:
`2025-05-01 14:52:38.494 WARNING (MainThread) [custom_components.tuya_local.climate] electriq_ecosilent14hpw_aircon.yaml/climate: Unrecognised HVAC Mode of True ignored`

> The order of hvac_mode within the config has no impact on functionality, and they are anyway sorted alphabetically or presented in a fixed order in the UI, depending on which card is used.

From a UI perspective, this is correct, but not from a processing perspective. 

https://github.com/make-all/tuya-local/blob/dda598f81b6ef650485ae664efbf1797dab9b5f0/custom_components/tuya_local/helpers/device_config.py#L547-L554

https://github.com/make-all/tuya-local/blob/dda598f81b6ef650485ae664efbf1797dab9b5f0/custom_components/tuya_local/helpers/device_config.py#L584

https://github.com/make-all/tuya-local/blob/dda598f81b6ef650485ae664efbf1797dab9b5f0/custom_components/tuya_local/climate.py#L354-L359

While yeah, it doesn't impact the UI, in `_find_map_for_dps` and `_find_map_for_value`, the code iterates through mappings in the order they appear. 

https://github.com/make-all/tuya-local/blob/dda598f81b6ef650485ae664efbf1797dab9b5f0/custom_components/tuya_local/helpers/device_config.py#L684-L693

When multiple mappings could match the first matching one is used. This is why we see "Unrecognised HVAC Mode of True ignored" and the behaviour of when you set the device in HA to `Auto`, it results in `Cool` on the device.

**Comment by make-all** [comment]
Are you using the latest config from after the previous PR was closed?

**Comment by XargsUK** [comment]
Yeah, for the 14HPW I was using your most current version in this repo after the PR was closed. For 12HPW, I was using my repo with the upstream merged in (up to commit dda598f81b6ef650485ae664efbf1797dab9b5f0)

**Comment by make-all** [comment]
Please download the diagnostics from the device when you put it into Auto mode from the device.
