### ISSUE TITLE
Madimack Inverflow Pro pump not working after recent update

### ISSUE THREAD

**Issue by rktdno** [make-all/tuya-local#3584]
### Description

Apologies if I should report this as a new device--I'm happy to if that's more appropriate, but given it was working I thought I'd report it as a bug. 

I've got four Madimack Inverflow Pro pumps (https://madimack.com/au/products/pool-pumps/inverflow-pro) which were connected and working through Tuya Local. As best I can tell, after a recent update to Tuya Local (I'm not 100% sure that was the cause, but the timing is consistent with the update) they now aren't connected/can't be set up again. They are otherwise functioning manually as well as in the Tuya app. 

I've attached a screenshot of the dashboard of one now which does show some of what was exposed to Home Assistant, but it is disconnected. Please let me know what further information I can supply or if I should be pointed in another direction.

<img width="546" height="682" alt="Image" src="https://github.com/user-attachments/assets/244f081e-2471-4455-8c87-fefbd6d1518f" />

### Expected behaviour

Pumps were previously working/connecting, but aren't currently

### Additional context

<img width="544" height="470" alt="Image" src="https://github.com/user-attachments/assets/7674816f-5d17-4a24-8691-71021bf34ef6" />

<img width="1099" height="729" alt="Image" src="https://github.com/user-attachments/assets/8b65fd80-4d7b-400d-89ea-299d7eabee2b" />

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [ ] If this is for a specific device, the device config filename is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.

**Comment by make-all** [comment]
There are no log messages here, so I cannot say what is happening.

There has been no change to this specific config since April, so it is not a change specific to this device. The only change that would affect behaviour here is that the integration now uses HA's delayed initialisation mechanism when a device is unavailable at startup instead of reporting success to HA and retrying internally.  But that will only change some status displays from "Unknown" to "Unavailable" when the device has been offline since startup.

**Comment by stewface** [comment]
@rktdno how did you get your Madimack pool pump added to Tuya I can’t figure out the right device to use

**Comment by rktdno** [comment]
@stewface I added them first in the tuya app on iOS--I can't recall the button sequence you press on the pump to put it into pair mode (a long press of one of the buttons if I recall) and then you can add it in tuya local. As you can see in the screenshot above I've got a few that are paired and working. They are the Inverflow Pro https://madimack.com/au/products/pool-pumps/inverflow-pro

Which reminds me, the above issue was resolved with some of the later releases of tuya local. Whether intentional or not, thanks so much @make-all generally for the work on the integrations, it's really helpful.

**Comment by stewface** [comment]
Thanks for coming back @rktdno  I can easily get it into pairing mode, and I can see it make a wifi network **iGardenXXXX** 

Using the Madimac app I realised that it uses BLE to pair, but that hasn't helped me figure out the device to choose in the Tuya app. I've tried half a dozen options but nothing pairs. 

<img width="660" height="1434" alt="Image" src="https://github.com/user-attachments/assets/2643d60f-5132-4b0e-87ce-be5869e37599" />

E.g. water pump doesn't work, neither does generic etc. No sign of pool pump and I have looked in all the menus. 

I've got the inverflow **plus** I hope that plus isn't going to turn out to be a huge NEGATIVE :( 

<img width="583" height="300" alt="Image" src="https://github.com/user-attachments/assets/4a2b3032-9fe4-4c80-a489-3f433d521bc1" />

**Comment by rktdno** [comment]
Not sure how much help I can be—the Tuya app just recognises it as a pump. You can even see from the icon which is auto populated. 

![Image](https://github.com/user-attachments/assets/075dc6d2-74ab-432c-acb4-2aa16eac1d00)

So for me it was pretty seamless. Not sure that’s much help sadly.

**Comment by stewface** [comment]
Thanks @rktdno certainly helpful but I still can't get it going, I've been trying to get in contact with Madimac, they have been responsive but haven't been able to solve it yet. I'm hoping I can track down someone who connected / built the app.

**Comment by davidjac** [comment]
Any update on this?
