### ISSUE TITLE
Migration error with BEOK thermostats since version 2025.11.2

### ISSUE THREAD

**Issue by krany87** [make-all/tuya-local#4130]
### Description

Hi,
I’m experiencing issues

![Image](https://github.com/user-attachments/assets/86de92c2-4d7f-4d4e-a4d7-31c8ae9d4f67)

![Image](https://github.com/user-attachments/assets/1e130548-7da2-48fe-a5fe-51c6f975905d)

 after updating beyond version 2025.11.1.

I have three identical BEOK thermostats. With version 2025.11.1, all of them worked without any problems.
After updating to 2025.11.2, two out of the three thermostats started showing the following error message:

> Migration error:
Check the logs

I tried all available protocol versions, including the automatic option, but the two affected devices would not work anymore.
I then downgraded back to 2025.11.1, and everything immediately worked again.

Today I tested the new 2025.12 release, but unfortunately the exact same issue occurs again (see screenshot).

Do you have any idea what might be causing this or what I could try to resolve it?

Thanks in advance.

### Additional context

Logger: homeassistant.config_entries
Quelle: config_entries.py:1110
Erstmals aufgetreten: 20:10:24 (2 Vorkommnisse)
Zuletzt protokolliert: 20:10:25

Error migrating entry Thermostat Wohnküche Local for tuya_local
Error migrating entry Thermostat Schlafzimmer Local for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1110, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 667, in async_migrate_entry
    await async_migrate_entries(hass, entry.entry_id, update_unique_id13_10)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1973, in async_migrate_entries
    ent_reg.async_update_entity(entry.entity_id, **updates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1413, in async_update_entity
    return self._async_update_entity(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        entity_id,
        ^^^^^^^^^^
    ...<22 lines>...
        unit_of_measurement=unit_of_measurement,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1351, in _async_update_entity
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Unique id 'None-number_temperature_calibration' is already in use by 'number.thermostat_kinderzimmer_local_calibration_offset'

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config filename is mentioned above, or diagnostics are included.

- [x] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.

**Comment by make-all** [comment]
I don't know how the device ids have become None during the migration. Maybe a debug log will show more.

**Comment by make-all** [comment]
I think I see the issue, HA is no longer populating the unique_id field in the config entries database for the device, only my older devices have it. So when migrating, the "old_id" read by the migration code is missing and becomes None which is then used to construct the new IDs.

**Comment by timothy-gibson** [comment]
Hi @make-all , is there a workaround for populating the unique_id field beyond downgrading? I've just updated to 2025.12.3 and my Tuya devices are exhibiting the same issue.

**Comment by make-all** [comment]
Removing and re-adding the devices should work (the unique_id of the device will still be null, but the entities will be created using the actual device_id from the config flow, not recreated using the unique id of the existing device registry entry, and by the time another migration is needed, this issue will have been fixed. Or, if I can get a new release with a fix out today, you can wait and upgrade to 2025.12.1.

**Comment by timothy-gibson** [comment]
Thanks for the prompt response. I've downgraded HA back to 2025.11.3 for the moment and will hold updating to 2025.12.x until you've had a chance to make a release fix. Thanks again for your support on this integration it's been fantastic to use!

**Comment by JabeBRD** [comment]
Just upgraded HA to 2025.12.3 and Tuya_local to 2025.12.1, now im getting this same error.
```
Logger: homeassistant.config_entries
Source: config_entries.py:1110
First occurred: 19:37:22 (1 occurrence)
Last logged: 19:37:22

Error migrating entry Thermostat for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1110, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 702, in async_migrate_entry
    await async_migrate_entries(hass, entry.entry_id, update_unique_id3_11)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1973, in async_migrate_entries
    ent_reg.async_update_entity(entry.entity_id, **updates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1413, in async_update_entity
    return self._async_update_entity(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        entity_id,
        ^^^^^^^^^^
    ...<22 lines>...
        unit_of_measurement=unit_of_measurement,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1351, in _async_update_entity
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Unique id 'bf6d20d68fe2cdb581c5mk-number_temperature_calibration' is already in use by 'number.thermostat_temperature_calibration'
```
Removed and re-added, now device is working.

**Comment by make-all** [comment]
It is possible that when the wrong ids are migrated, HA also recreates the entities with good ids and leaves the invalid ones as inactive entities. In that case a better approach will be to just remove the invalid ids.

**Comment by krany87** [comment]
Hi,

unfortunately I’m still facing an issue with one out of three identical BEOK thermostats.
After your recent fix, two thermostats are working correctly again, but the third one cannot be added anymore.

**What I already tried (as recommended):**
- Removed the affected device from the Tuya Local integration
- Verified that no entities related to this thermostat exist anymore
- Restarted Home Assistant
- Tried to add the thermostat again using the same IP, Device ID and Local Key

**Current behavior:**
During setup, Home Assistant shows the following error:
“_With these credentials, a connection to your device cannot be established.
This may be an intermittent problem, or the credentials are incorrect._”

**Why I believe hardware and credentials are not the issue:**
- The thermostat communicates correctly with the official Tuya app
- I can control and monitor it there without any issues
- This strongly suggests the hardware, network connectivity, and device itself are working
- The other two thermostats (same model, same firmware) work fine with Tuya Local

**Relevant Home Assistant log:**
"This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:651
Integration: Tuya Local
First occurred: 16:56:48 (7 occurrences)
Last logged: 17:08:29

Failed to refresh device state for Test."

Do you have any idea what else could still be blocking the setup?

Thanks a lot for your help and for maintaining this integration.

**Comment by make-all** [comment]
See #522, likely your mobile app is blocking the connection, or some of the details have changed from what you are entering.
